name: Build PCT React Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install yarn
        run: npm install -g yarn

      - name: Install the dependencies
        run: yarn install

      - name: Testing
        run: yarn test:nowatch

      - name: Build the production files
        run: yarn build