name: Build PCT React Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install yarn
        run: npm install -g yarn

      - name: Install the dependencies
        run: yarn install

      - name: Testing
        run: yarn test:nowatch

      - name: Build the production files
        run: yarn build

      - name: Deploy to s3 bucket
        run: aws s3 sync ./build s3://new.pingchengtech.com --dryrun --delete --acl public-read