name: Build PCT React Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
      REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID }}
      REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install the dependencies
        run: npm install

      - name: Run code lint
        run: npm run lint

      - name: Testing
        run: npm run test:nowatch -- --coverage

      - name: Build the production files
        run: npm run build

      # publish coverage
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: pct-frontend-test-coverage
          path: './coverage'

      # publish
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: pct-frontend-build
          path: './build'

  deploy-production:
    runs-on: ubuntu-latest
    environment: 'deploy-production'
    needs: build
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pct-frontend-build
          path: './build'

      - name: Deploy to s3 bucket
        run: aws s3 sync ./build s3://pingchengtech.com --delete --acl public-read

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"